### ISSUE TITLE
Ability to Automatically Adjust THG (Serial Laser Control)

### ISSUE THREAD

**Issue by jdshutter** [nthallen/keutsch-hcho#1]
Instead of having to manually change the THG value, it would be nice to have serial control of the laser to allow for greater instrument autonomy. THG correction is highly useful since we want the online and offline positions to have the same laser power.

THG Correction (Two Scenarios)

**Scenario 1**: For an _offline delta shift_ equal to a positive integer:
If online power > offline power, then THG should increase
If online power < offline power, then THG should decrease

**Scenario 2**: for an _offline delta shift_ equal to a negative integer:
If online power > offline power, then THG should decrease
If online power < offline power, then THG should increase

The magnitude of THG correction is generally on the order of 0.01 deg C.

**Comment by nthallen** [comment]
Baudrate: 38.4 K

Command:
```
WTHGxxxx xxxx = 2500 = 25.00C (3000 only)
LN Laser On
LF Laser Off
```
To request status:
```
S15 xx.xx C THG Temperature (3000 only)
```

**Comment by jdshutter** [comment]
Tested and working
