### ISSUE TITLE
Overflow Condition for Zero and Span Flow Readings

### ISSUE THREAD

**Issue by jdshutter** [nthallen/keutsch-hcho#12]
An overflow condition is appearing when the zero and span MFC flow readouts are too high. As a result, they're not appearing in the raw data files.

The MFC setpoints are being reported fine.

**Comment by nthallen** [comment]
Can you give me a run number and approximate time when the overflow condition occurs?

**Comment by jdshutter** [comment]
180423.1 is the experimental run

FC0_Flow and FC1_Flow were both affected.

Entire dataset is affected, but one time was 1.5243692457e9 seconds

**Comment by nthallen** [comment]
I have implemented a fix that should resolve this. It is compiled on hclgse, ready for distribution and testing.
