### ISSUE TITLE
PwrOut Label Change

### ISSUE THREAD

**Issue by jdshutter** [nthallen/keutsch-hcho#3]
The value being readout under Laser Control >> PwrOut is actually from the power meter located right before the laser pulse enters the single-pass cell. 

Thus, could the labels PwrIn and PwrOut be switched?

**Comment by nthallen** [comment]
- [x] Try to swap the device addresses using the dip switches. If that works, we're done.
 - [ ] Otherwise we can swap the addresses in software and firmware

**Comment by jdshutter** [comment]
I physically swapped the two power meters and documented their dip switch positions (see below). Everything is working fine, so I'm going to close this issue.

LasPwrIn Address: 0 x 0 x 1
LasPwrOut Address: 0 x 1 x 0
